# Generated by Django 2.2.6 on 2024-02-20 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cruds', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='season',
            name='comisioners',
            field=models.ManyToManyField(to='cruds.Comisioner'),
        ),
    ]
