# Generated by Django 2.2.6 on 2024-03-04 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cruds', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='season',
            name='faculties',
            field=models.ManyToManyField(to='cruds.Faculty'),
        ),
    ]
