# Generated by Django 2.2.6 on 2024-03-19 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cruds', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commissioner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('position', models.CharField(max_length=200)),
                ('biography', models.TextField()),
                ('picture', models.ImageField(upload_to='news_pictures/')),
                ('comition', models.CharField(choices=[('disciplinariaP', 'disciplinariaP'), ('disciplinariaS', 'disciplinariaS'), ('organizativa', 'organizativa')], max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='season',
            name='comisioners',
        ),
        migrations.AlterField(
            model_name='team',
            name='medal',
            field=models.CharField(blank=True, choices=[('Oro', 'Oro'), ('Plata', 'Plata'), ('Bronce', 'Bronce')], max_length=200, null=True),
        ),
        migrations.DeleteModel(
            name='Comisioner',
        ),
        migrations.AddField(
            model_name='season',
            name='commissioners',
            field=models.ManyToManyField(to='cruds.Commissioner'),
        ),
    ]
