# Generated by Django 2.2.6 on 2024-02-20 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cruds', '0002_season_comisioners'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='season',
            name='comisioners',
        ),
    ]
