# Generated by Django 2.2.6 on 2024-03-04 01:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cruds', '0002_season_faculties'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='sport',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='games', to='cruds.Sport'),
            preserve_default=False,
        ),
    ]
