# Generated by Django 2.2.6 on 2024-02-20 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cruds', '0003_remove_season_comisioners'),
    ]

    operations = [
        migrations.AddField(
            model_name='season',
            name='comisioners',
            field=models.ManyToManyField(to='cruds.Comisioner'),
        ),
    ]
