# Generated by Django 2.2.6 on 2024-03-04 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cruds', '0005_documents'),
        ('cruds', '0008_auto_20240303_2159'),
    ]

    operations = [
    ]
