# Generated by Django 2.2.6 on 2024-02-08 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(max_length=200, upload_to='')),
                ('tipo', models.CharField(max_length=30)),
            ],
        ),
    ]
