# Generated by Django 2.2.6 on 2024-02-09 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=30)),
            ],
        ),
        migrations.DeleteModel(
            name='Documento',
        ),
    ]
